package com.newgen.ibm.commons;


public class QuestService_UtilityHelper {
	public static String parentFolderIndex;
	public static String cabinetName;
	public static String serverIP;
	public static String serverPort;
	public static String jtsIP;
	public static int jtsPort;
	public static String userName;
	public static String userPassword;
	public static String sessionID;
	public static String processDefID;
	public static String processDefID1;
	public static String constDataClassName;
	public static String constAOFDoc;
	public static String constIntroMedAUTO;
	public static String constIntroMedOC;
	public static String userID;
	public static String DocNameAOF;
	public static String dataDefIndex = "";
	public static String siteID;
	public static String constantDataClassCIF;
	public static String constantDataClassAOF;
	public static String constCIFDoc;
	public static String AccountNOPath;
	public static String CustomerIDPath;
	public static String service_LOG;
	public static String[] TxtFileValues;
	public static String ProcessName;
	public static String ProcessDef;
	public static String VolumeName;
	public static String VolumeID;
	public static String IntroActivityName;
	public static String FilePath;
	public static String PurchaseWithCAF;
	public static String PurchaseWithoutCAF;
	public static String LogPath;
	public static String PollingInterval;
	public static String LogSize;
	public static String EnableLog;
	public static String path;
	public static String BatchName;
	public static String QueueIDGRV = "";
	public static String BatchSize="5";
	public static String ItemIndex;
	public static String DumpPath;
	public static String sDateFolderFormat;
	public static String SuccessLogPath;
	public static String ErrorLogPath;
	public static String WSEndpointURL;
	public static long LOG_FILESIZE;
}
